AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "*.gemspec"
plugins:
  - rubocop-rake
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
