# frozen_string_literal: true

require "stringio"

module OllamaAgent
  module SelfImprovement
    # Optional markdown report from the `ruby_mastery` gem, prepended to self_review / improve prompts.
    module RubyMasteryContext
      class << self
        def markdown_section(root)
          return nil if root.to_s.strip.empty?
          return nil unless File.directory?(root)
          return nil unless load_gem

          body = report_markdown_captured(root)
          return nil if body.nil? || body.strip.empty?

          wrap_truncated(body, max_body_chars)
        rescue StandardError => e
          warn "ollama_agent: ruby_mastery skipped (#{e.class}: #{e.message})"
          nil
        end

        private

        def load_gem
          require "ruby_mastery"
          true
        rescue LoadError
          false
        end

        def report_markdown_captured(root)
          previous = $stdout
          $stdout = StringIO.new
          RubyMastery.report(root, format: :markdown)
        ensure
          $stdout = previous
        end

        def max_body_chars
          raw = ENV.fetch("OLLAMA_AGENT_RUBY_MASTERY_MAX_CHARS", "60000").to_i
          raw.positive? ? raw : 60_000
        end

        def wrap_truncated(body, limit)
          text = body.to_s
          excerpt = if text.length > limit
                      "#{text[0, limit].rstrip}\n\n" \
                        "_(truncated; set OLLAMA_AGENT_RUBY_MASTERY_MAX_CHARS to raise the limit)_"
                    else
                      text
                    end

          <<~MARKDOWN.strip
            ## Static analysis (ruby_mastery)

            The following was generated by the `ruby_mastery` gem. Treat it as one signal alongside your own reads of the code.

            #{excerpt}
          MARKDOWN
        end
      end
    end
  end
end
